// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type FlightPageDocumentDataSlicesSlice = never;

/**
 * Content for flight_page documents
 */
interface FlightPageDocumentData {
  /**
   * Slice Zone field in *flight_page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: flight_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FlightPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *flight_page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: flight_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *flight_page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: flight_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *flight_page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: flight_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * flight_page document from Prismic
 *
 * - **API ID**: `flight_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FlightPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FlightPageDocumentData>,
    "flight_page",
    Lang
  >;

type FlightsLandingDocumentDataSlicesSlice = never;

/**
 * Content for flights_landing documents
 */
interface FlightsLandingDocumentData {
  /**
   * Slice Zone field in *flights_landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: flights_landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FlightsLandingDocumentDataSlicesSlice>; /**
   * Meta Title field in *flights_landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: flights_landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *flights_landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: flights_landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *flights_landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: flights_landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * flights_landing document from Prismic
 *
 * - **API ID**: `flights_landing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FlightsLandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FlightsLandingDocumentData>,
    "flights_landing",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * sample field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.sample
   * - **Tab**: Home
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sample: prismic.KeyTextField;

  /**
   * sample1 field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.sample1
   * - **Tab**: Home
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sample1: prismic.KeyTextField;

  /**
   * test field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.test
   * - **Tab**: Home
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  test: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Home
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>; /**
   * flight select field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.flight_select
   * - **Tab**: Flight Select
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  flight_select: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type HomepageDocumentDataSlicesSlice =
  | HeroBannerSlice
  | SectionHeaderSlice
  | FeaturedFlightsSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slices field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | FlightPageDocument
  | FlightsLandingDocument
  | HomeDocument
  | HomepageDocument;

/**
 * Primary content in *FeaturedFlights → Default → Primary*
 */
export interface FeaturedFlightsSliceDefaultPrimary {
  /**
   * Section Title field in *FeaturedFlights → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_flights.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Max Items field in *FeaturedFlights → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 4
   * - **API ID Path**: featured_flights.default.primary.max_items
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  max_items: prismic.NumberField;
}

/**
 * Default variation for FeaturedFlights Slice
 *
 * - **API ID**: `default`
 * - **Description**: Section configuration for featured flights list rendering.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedFlightsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedFlightsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedFlights*
 */
type FeaturedFlightsSliceVariation = FeaturedFlightsSliceDefault;

/**
 * FeaturedFlights Shared Slice
 *
 * - **API ID**: `featured_flights`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedFlightsSlice = prismic.SharedSlice<
  "featured_flights",
  FeaturedFlightsSliceVariation
>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Headline field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary Button Label field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Label field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Homepage hero content with primary and secondary CTA buttons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Item in *HeroWithMetricsCards → Default → Primary → Metric Cards*
 */
export interface HeroWithMetricsCardsSliceDefaultPrimaryMetricsItem {
  /**
   * Metric Label field in *HeroWithMetricsCards → Default → Primary → Metric Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.metrics[].metric_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  metric_label: prismic.KeyTextField;

  /**
   * Metric Value field in *HeroWithMetricsCards → Default → Primary → Metric Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.metrics[].metric_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  metric_value: prismic.KeyTextField;
}

/**
 * Primary content in *HeroWithMetricsCards → Default → Primary*
 */
export interface HeroWithMetricsCardsSliceDefaultPrimary {
  /**
   * Eyebrow field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary Actions field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.primary_actions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_actions: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "primary" | "secondary"
    >
  >;

  /**
   * Metric Cards field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.metrics[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  metrics: prismic.GroupField<
    Simplify<HeroWithMetricsCardsSliceDefaultPrimaryMetricsItem>
  >;
}

/**
 * Default variation for HeroWithMetricsCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero section with headline, description, action buttons, and several statistical/metrics cards displayed in a row below the actions.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithMetricsCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithMetricsCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroWithMetricsCards*
 */
type HeroWithMetricsCardsSliceVariation = HeroWithMetricsCardsSliceDefault;

/**
 * HeroWithMetricsCards Shared Slice
 *
 * - **API ID**: `hero_with_metrics_cards`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithMetricsCardsSlice = prismic.SharedSlice<
  "hero_with_metrics_cards",
  HeroWithMetricsCardsSliceVariation
>;

/**
 * Primary content in *SectionHeader → Default → Primary*
 */
export interface SectionHeaderSliceDefaultPrimary {
  /**
   * Title field in *SectionHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *SectionHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for SectionHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Reusable title and subtitle block for homepage sections.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionHeader*
 */
type SectionHeaderSliceVariation = SectionHeaderSliceDefault;

/**
 * SectionHeader Shared Slice
 *
 * - **API ID**: `section_header`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionHeaderSlice = prismic.SharedSlice<
  "section_header",
  SectionHeaderSliceVariation
>;

/**
 * Primary content in *Test → Default → Primary*
 */
export interface TestSliceDefaultPrimary {
  /**
   * sample field in *Test → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: test.default.primary.sample
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sample: prismic.RichTextField;

  /**
   * image field in *Test → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Test Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Test*
 */
type TestSliceVariation = TestSliceDefault;

/**
 * Test Shared Slice
 *
 * - **API ID**: `test`
 * - **Description**: Test
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestSlice = prismic.SharedSlice<"test", TestSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FlightPageDocument,
      FlightPageDocumentData,
      FlightPageDocumentDataSlicesSlice,
      FlightsLandingDocument,
      FlightsLandingDocumentData,
      FlightsLandingDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      FeaturedFlightsSlice,
      FeaturedFlightsSliceDefaultPrimary,
      FeaturedFlightsSliceVariation,
      FeaturedFlightsSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      HeroWithMetricsCardsSlice,
      HeroWithMetricsCardsSliceDefaultPrimaryMetricsItem,
      HeroWithMetricsCardsSliceDefaultPrimary,
      HeroWithMetricsCardsSliceVariation,
      HeroWithMetricsCardsSliceDefault,
      SectionHeaderSlice,
      SectionHeaderSliceDefaultPrimary,
      SectionHeaderSliceVariation,
      SectionHeaderSliceDefault,
      TestSlice,
      TestSliceDefaultPrimary,
      TestSliceVariation,
      TestSliceDefault,
    };
  }
}
