// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Flight Page documents
 */
interface FlightPageDocumentData {
  /**
   * Flight Code field in *Flight Page*
   *
   * - **Field Type**: UID
   * - **Placeholder**: *None*
   * - **API ID Path**: flight_page.flight_code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/uid
   */

  /**
   * Route Name field in *Flight Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Dubai to London
   * - **API ID Path**: flight_page.route_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  route_name: prismic.KeyTextField;

  /**
   * Short Description field in *Flight Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief flight details
   * - **API ID Path**: flight_page.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_description: prismic.KeyTextField;
}

/**
 * Flight Page document from Prismic
 *
 * - **API ID**: `flight_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FlightPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FlightPageDocumentData>,
    "flight_page",
    Lang
  >;

/**
 * Content for Flights Landing documents
 */
interface FlightsLandingDocumentData {
  /**
   * Page Title field in *Flights Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Flights
   * - **API ID Path**: flights_landing.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page Description field in *Flights Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Browse SkyBridge Air routes
   * - **API ID Path**: flights_landing.page_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_description: prismic.KeyTextField; /**
   * Meta Title field in *Flights Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Flights | SkyBridge Air
   * - **API ID Path**: flights_landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Flights Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Browse routes with server-rendered availability and fares.
   * - **API ID Path**: flights_landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Flights Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: flights_landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Canonical URL field in *Flights Landing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: flights_landing.canonical_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  canonical_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Flights Landing document from Prismic
 *
 * - **API ID**: `flights_landing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FlightsLandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FlightsLandingDocumentData>,
    "flights_landing",
    Lang
  >;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Brand Name field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SkyBridge Air
   * - **API ID Path**: homepage.brand_name
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  brand_name: prismic.KeyTextField;

  /**
   * Nav Book Flights Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book Flights
   * - **API ID Path**: homepage.nav_book_flights_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_book_flights_label: prismic.KeyTextField;

  /**
   * Nav Manage Booking Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Manage Booking
   * - **API ID Path**: homepage.nav_manage_booking_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_manage_booking_label: prismic.KeyTextField;

  /**
   * Nav Travel Info Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Travel Info
   * - **API ID Path**: homepage.nav_travel_info_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_travel_info_label: prismic.KeyTextField;

  /**
   * Nav Support Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Support
   * - **API ID Path**: homepage.nav_support_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_support_label: prismic.KeyTextField;

  /**
   * Currency Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: USD ($)
   * - **API ID Path**: homepage.currency_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  currency_label: prismic.KeyTextField;

  /**
   * Language Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: English
   * - **API ID Path**: homepage.language_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  language_label: prismic.KeyTextField;

  /**
   * Club Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SkyBridge Club
   * - **API ID Path**: homepage.club_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  club_label: prismic.KeyTextField;

  /**
   * Login Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Login
   * - **API ID Path**: homepage.login_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  login_label: prismic.KeyTextField; /**
   * Page Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SkyBridge Air
   * - **API ID Path**: homepage.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search routes, compare fares, and book your next journey with SkyBridge Air.
   * - **API ID Path**: homepage.page_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_description: prismic.KeyTextField;

  /**
   * Hero Headline field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book your next flight with confidence.
   * - **API ID Path**: homepage.hero_headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_headline: prismic.KeyTextField;

  /**
   * Hero Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search live routes, review fares, and manage your trip from one streamlined booking experience.
   * - **API ID Path**: homepage.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_description: prismic.KeyTextField;

  /**
   * Primary Button Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search flights
   * - **API ID Path**: homepage.primary_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * Primary Button Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.primary_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Manage booking
   * - **API ID Path**: homepage.secondary_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.secondary_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >; /**
   * One Way Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: One way
   * - **API ID Path**: homepage.one_way_label
   * - **Tab**: Search Widget
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  one_way_label: prismic.KeyTextField;

  /**
   * Round Trip Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Round trip
   * - **API ID Path**: homepage.round_trip_label
   * - **Tab**: Search Widget
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  round_trip_label: prismic.KeyTextField;

  /**
   * Origin Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Departure
   * - **API ID Path**: homepage.origin_label
   * - **Tab**: Search Widget
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  origin_label: prismic.KeyTextField;

  /**
   * Destination Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Arrival
   * - **API ID Path**: homepage.destination_label
   * - **Tab**: Search Widget
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  destination_label: prismic.KeyTextField;

  /**
   * Passenger Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Passengers
   * - **API ID Path**: homepage.passenger_label
   * - **Tab**: Search Widget
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  passenger_label: prismic.KeyTextField;

  /**
   * Date Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Date
   * - **API ID Path**: homepage.date_label
   * - **Tab**: Search Widget
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_label: prismic.KeyTextField;

  /**
   * Promo Code Label field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add promo code
   * - **API ID Path**: homepage.promo_code_label
   * - **Tab**: Search Widget
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  promo_code_label: prismic.KeyTextField;

  /**
   * Search Button Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search flights
   * - **API ID Path**: homepage.search_button_text
   * - **Tab**: Search Widget
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  search_button_text: prismic.KeyTextField; /**
   * Routes Live field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 3
   * - **API ID Path**: homepage.routes_live
   * - **Tab**: API Metrics
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  routes_live: prismic.NumberField;

  /**
   * Average Fare field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 455.67
   * - **API ID Path**: homepage.average_fare
   * - **Tab**: API Metrics
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  average_fare: prismic.NumberField;

  /**
   * On-time Performance (%) field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 96
   * - **API ID Path**: homepage.on_time_performance
   * - **Tab**: API Metrics
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  on_time_performance: prismic.NumberField;

  /**
   * Updated At field in *Homepage*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.updated_at
   * - **Tab**: API Metrics
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  updated_at: prismic.TimestampField; /**
   * Footer Support Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Need help? SkyBridge Air is here to support your journey.
   * - **API ID Path**: homepage.footer_support_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_support_text: prismic.KeyTextField;

  /**
   * Footer Copyright field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Copyright © SkyBridge Air.
   * - **API ID Path**: homepage.footer_copyright
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_copyright: prismic.KeyTextField; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SkyBridge Air | Book flights online
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search routes, compare fares, and book flights with SkyBridge Air.
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | FlightPageDocument
  | FlightsLandingDocument
  | HomepageDocument;

/**
 * Primary content in *FeaturedFlights → Default → Primary*
 */
export interface FeaturedFlightsSliceDefaultPrimary {
  /**
   * Section Title field in *FeaturedFlights → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_flights.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Max Items field in *FeaturedFlights → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 4
   * - **API ID Path**: featured_flights.default.primary.max_items
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  max_items: prismic.NumberField;
}

/**
 * Default variation for FeaturedFlights Slice
 *
 * - **API ID**: `default`
 * - **Description**: Section configuration for featured flights list rendering.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedFlightsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedFlightsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedFlights*
 */
type FeaturedFlightsSliceVariation = FeaturedFlightsSliceDefault;

/**
 * FeaturedFlights Shared Slice
 *
 * - **API ID**: `featured_flights`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedFlightsSlice = prismic.SharedSlice<
  "featured_flights",
  FeaturedFlightsSliceVariation
>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Headline field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary Button Label field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.primary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_label: prismic.KeyTextField;

  /**
   * Primary Button Link field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Label field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.secondary_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_label: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Kavin field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.kavin
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  kavin: prismic.KeyTextField;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Homepage hero content with primary and secondary CTA buttons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Item in *HeroWithMetricsCards → Default → Primary → Metric Cards*
 */
export interface HeroWithMetricsCardsSliceDefaultPrimaryMetricsItem {
  /**
   * Metric Label field in *HeroWithMetricsCards → Default → Primary → Metric Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.metrics[].metric_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  metric_label: prismic.KeyTextField;

  /**
   * Metric Value field in *HeroWithMetricsCards → Default → Primary → Metric Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.metrics[].metric_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  metric_value: prismic.KeyTextField;
}

/**
 * Primary content in *HeroWithMetricsCards → Default → Primary*
 */
export interface HeroWithMetricsCardsSliceDefaultPrimary {
  /**
   * Eyebrow field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary Actions field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.primary_actions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_actions: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "primary" | "secondary"
    >
  >;

  /**
   * Metric Cards field in *HeroWithMetricsCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_metrics_cards.default.primary.metrics[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  metrics: prismic.GroupField<
    Simplify<HeroWithMetricsCardsSliceDefaultPrimaryMetricsItem>
  >;
}

/**
 * Default variation for HeroWithMetricsCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero section with headline, description, action buttons, and several statistical/metrics cards displayed in a row below the actions.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithMetricsCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithMetricsCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroWithMetricsCards*
 */
type HeroWithMetricsCardsSliceVariation = HeroWithMetricsCardsSliceDefault;

/**
 * HeroWithMetricsCards Shared Slice
 *
 * - **API ID**: `hero_with_metrics_cards`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithMetricsCardsSlice = prismic.SharedSlice<
  "hero_with_metrics_cards",
  HeroWithMetricsCardsSliceVariation
>;

/**
 * Primary content in *SectionHeader → Default → Primary*
 */
export interface SectionHeaderSliceDefaultPrimary {
  /**
   * Title field in *SectionHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *SectionHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_header.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for SectionHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Reusable title and subtitle block for homepage sections.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionHeader*
 */
type SectionHeaderSliceVariation = SectionHeaderSliceDefault;

/**
 * SectionHeader Shared Slice
 *
 * - **API ID**: `section_header`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionHeaderSlice = prismic.SharedSlice<
  "section_header",
  SectionHeaderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FlightPageDocument,
      FlightPageDocumentData,
      FlightsLandingDocument,
      FlightsLandingDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      AllDocumentTypes,
      FeaturedFlightsSlice,
      FeaturedFlightsSliceDefaultPrimary,
      FeaturedFlightsSliceVariation,
      FeaturedFlightsSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      HeroWithMetricsCardsSlice,
      HeroWithMetricsCardsSliceDefaultPrimaryMetricsItem,
      HeroWithMetricsCardsSliceDefaultPrimary,
      HeroWithMetricsCardsSliceVariation,
      HeroWithMetricsCardsSliceDefault,
      SectionHeaderSlice,
      SectionHeaderSliceDefaultPrimary,
      SectionHeaderSliceVariation,
      SectionHeaderSliceDefault,
    };
  }
}
