// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_flights: dynamic(() => import("./FeaturedFlights")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  hero_with_metrics_cards: dynamic(() => import("./HeroWithMetricsCards")),
  section_header: dynamic(() => import("./SectionHeader")),
};
